### ISSUE TITLE
How to update for transformers-0.5?

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/transformers-compat#11]
`transformers-0.5` adds quite a few goodies that might prove tricky to backport in `transformers-compat`. Some questions:

* `transformers-0.5` completely redesigns `Eq1`/`Eq2`/etc. in the `Data.Functor.Classes` module. Unfortunately, `Data.Functor.Classes` has been around since `transformers-0.4`, so we can't simply backport these typeclasses to `transformers-compat`'s `Data.Functor.Classes` and have things work consistently across all versions of `transformers`.
* Similarly, consistently exporting `Eq1`/`Eq2`/etc. instances has become tricky. #9 is one example; there are probably others.

Might we need to reorganize the modules in `transformers-compat` a little bit? A comment in #9 provides one suggestion, but I'm not really sure myself what the best choice is.

**Comment by svenpanne** [comment]
Whatever needs to be done, it should be done relatively quickly, because there are currently [84 reverse dependencies](http://packdeps.haskellers.com/reverse/transformers-compat) of transformers-compat, and much more stuff is broken transitively, see e.g. pcapriotti/optparse-applicative#174.

Put another way: I would prefer any quick solution which unbreaks things over a polished shiny new API in the distant future. The upcoming GHC 8.0 is really a horror from a maintenance POV... :stuck_out_tongue:

**Comment by ekmett** [comment]
The goal of `transformers-compat` is for compatibility with as much of whatever is the latest version of transformers that we can give users.

However, we can't give `Data.Functor.Classes` in a transparent way that includes 0.4. Users will experience some CPP pain if they want to define the instances.

We can make it so that on `transformers < 0.4` we give `Data.Functor.Classes` ourselves with the current API, then make it so that on 0.4 we leave it alone because we can't put anything in that module, and on 0.5 they'd get it from transformers or base anyways.

So the main thing to update would be that in the `Data.Functor.Classes` module we have to match the new `base` / `transformers` behavior.

**Comment by RyanGlScott** [comment]
OK. What does that mean for `transformers-0.4` users? Will they need to
find some other way to get the new `Data.Functor.Classes` typeclasses?

I ask since I was thinking of upgrading one of my libraries to use them,
but that might mean dropping support for GHC 7.10...

**Comment by ekmett** [comment]
I think that transformers 0.4 users will need to CPP around which of the two definitions they get.

```haskell
#if MIN_VERSION_transformers(0,4,0) && !MIN_VERSION_transformers(0,5,0)
  0.4-compatible version of code
#else
  0.5-compatible version of code
#endif
```

... since we can't fix the 0.4 definitions.

**Comment by RyanGlScott** [comment]
As far as Data.Functor.Classes goes, that's probably the only way to handle
it. But it feels a bit disjointed to only have these typeclasses available
with transformers < 0.4 && >= 0.5. Couldn't we put the backported
typeclasses into, say, Data.Functor.Classes.Compat for all old versions of
transformers, and then conditionally reexport them from
Data.Functor.Classes? That way, we could still maintain the module-naming
conventions of old, while still providing an alternate path for those who
need them.

**Comment by ekmett** [comment]
The problem then is we're asking folks to implement two sets of instances.
One for our classes and one for the "real" classes.

**Comment by RyanGlScott** [comment]
That's true. It's not going to be pretty looking at all of the pragma soup I'll need to use `Data.Functor.Classes` from hereon out, but I suppose there's not much one can do about that.

I've opened #12 to make `transformers-compat` compliant with `transformers-0.5.0.0`.

**Comment by hvr** [comment]
@ekmett @RyanGlScott 

What's the status on a `transformers-compat` compatible with transformers-0.5? What's missing? any ETA? This is becoming a choke-point to get `tasty` and a few other popular packages working on GHC 8RC (which is to be released RSN by @bgamari)

(also, just as a reminder: my PPA already carries `ghc-8.0.1` & `cabal-install-1.24` packages)

**Comment by RyanGlScott** [comment]
I _think_ the HEAD version of `transformers-compat` is ready to work with `transformers-0.5`. Barring any sudden changes to `base` or `transformers`, it should be able to work with GHC 8.0.

I'm not sure about when a new Hackage release is due, though.

**Comment by ekmett** [comment]
I'm traveling in the morning, but I'll see if I can't get something out in the next couple of days. I want to ensure that I get this release right, because it involves shipping 4 versions of the package to preserve the very delicate cabal hack that makes it work, and if I get it wrong re-releasing will be messy.

**Comment by asr** [comment]
:+1:

**Comment by ekmett** [comment]
I think it is time to ship it.

**Comment by asr** [comment]
Thanks for releasing.
