### ISSUE TITLE
Version selection flags are marked "manual"

### ISSUE THREAD

**Issue by glguy** [ekmett/transformers-compat#29]
Why are the version flags `two`, `three`, `four`, and `five` marked as `manual`? Aren't they intended to be automatic flags? Merijn Verstraaten reports on #haskell on Freenode that a bug fix in Cabal is making this an issue now. Seems clear that we ought to change it, but since it was intentionally specified as manual I'm opening this ticket to ask the question.

cc @RyanGlScott @ekmett

**Comment by glguy** [comment]
Also cc @merijn

**Comment by RyanGlScott** [comment]
I can really only offer speculation here, but I strongly suspect the current design was motivated by bugs in (old versions of?) `cabal-install`. (See of the discussion [here](https://github.com/ekmett/transformers-compat/issues/10#issuecomment-169655572), for instance.)

I'd be curious to know what this new `cabal-install` fix is that is motivating this change.

**Comment by phadej** [comment]
@RyanGlScott yes, solver is smart enough to pick correct flag assignments, so single `transformers-compat` version would be enough.

That's the (my) whole motivation. From "multiple version + manual flags" to "single version + automatic flags". Latter is better.

**Comment by RyanGlScott** [comment]
Alright. In principle, I don't have any objection to this idea. @ekmett, what do you think?

**Comment by ekmett** [comment]
We used manual flags because the old cabal solver wasn't smart enough to backtrack chains of flag assignments to resolve the flag. The hack was put in place, and it worked for 3 flags, but now that we have 4-5, it seems like it has its own problems; I've been bitten by "no plan" complaints when using `transformers-compat` a couple of times since we added 0.6 support, but haven't been able to narrow it down nicely.

I'm all for a better solution. I'd be psyched if we could just require a modern enough version of cabal and just use flag backtracking the way the package was originally designed.

@phadej You said it finds a plan, but have you tried it with each of the old `transformers` version ranges individually pre-installed and had it automatically select the right branch? The old behavior only found problems in that sort of scenario.

**Comment by phadej** [comment]
@ekmett I'm not sure what you mean by pre-installed?

the #38 PR witnesses that GHC-bundled transformers are ok.

---

I run a `new-build` sweep with `--constraint=tranformers==version`

![screenshot from 2018-04-24 15-47-17](https://user-images.githubusercontent.com/51087/39187850-04d7634e-47d7-11e8-9e31-1a375ef2cd3b.png)

`new-build` finds the plan for each of those.

---

I also tried `cabal sandbox` with ghc-7.8.4:
- clean sanbox works
- after installing `transformers-0.4.1.0` also works
- after installing `transformers-0.5.5.0` also works
---

Note: `stack` users (to first approximation) never use non-bundled `transformers` versions, and anyway aren't affected by solver targeting changes.

**Comment by ekmett** [comment]
Since it seems to be working then by all means, let's simplify the package!

**Comment by RyanGlScott** [comment]
This was addressed in #38.
