### ISSUE TITLE
test suite failure with ghc 8.4

### ISSUE THREAD

**Issue by DanBurton** [ekmett/transformers-compat#32]
It is unclear to me whether this test failure has significance or not.

```
Failures:

  tests/GenericsSpec.hs:62:
  1) Generics.T# has a valid Read1 instance
       uncaught exception: ErrorCall (Prelude.read: no parse
       CallStack (from HasCallStack):
         error, called at tests/GenericsSpec.hs:49:18 in main:GenericsSpec) (after 4 tests)
       *** Failed! (after 4 tests):
       Exception:
         Prelude.read: no parse
         CallStack (from HasCallStack):
           error, called at tests/GenericsSpec.hs:49:18 in main:GenericsSpec
       MkT2# {getT2# = 1, (##) = -1}

Randomized with seed 1253242578

Finished in 0.0331 seconds
23 examples, 1 failure
```

**Comment by RyanGlScott** [comment]
Thank you for noticing this. It turns out this revealed a [GHC 8.4.1 bug](https://ghc.haskell.org/trac/ghc/ticket/14918).

Until I get a better understanding of what's going on here, I think it's probably best to keep this excluded from Stackage.

(Also, I really should figure out how to [run this test suite via Travis](https://github.com/ekmett/transformers-compat/issues/24)...)

**Comment by DanBurton** [comment]
I think I'll go against your advice and keep `transformers-compat` in the stackage nightly build plan for now. With a few exceptions (of test suites marked as skipped or expected failures for other reasons), the following list of transformer-compat's revdeps are known to build and pass their test suites:

```
- Glob
- adjunctions
- aeson-better-errors
- bifunctors
- bound
- bytes
- comonad
- constraints
- contravariant
- criterion
- cron
- deriving-compat
- distributive
- errors
- exceptions
- free
- graphs
- invariant
- jose-jwt
- kan-extensions
- keys
- lens
- linear
- machines
- microlens-mtl
- mmorph
- monad-control
- monad-coroutine
- monad-parallel
- monadic-arrays
- optparse-applicative
- pointed
- prompt
- quickcheck-instances
- recursion-schemes
- semigroupoids
- tagged
- these
- transformers-base
- unbound-generics
```

But if we get reports on any of these of weird behavior, we'll keep this issue in mind.

**Comment by RyanGlScott** [comment]
Sorry, I should have been more clear. I meant to say "keep the _test suite_ off of Stackage"—the library itself is fine!

And the test suite failure is only due to an infelicity in GHC itself—`transformers-compat` is doing everything it's supposed to correctly. Moreover, it's an extreme corner case, so it's pretty unlikely others would notice this. (Indeed, it went unnoticed until after 8.4.1's release.)

**Comment by DanBurton** [comment]
Ahh. Got it. Thanks for the clarification.
